### ISSUE TITLE
update Find method to treat case and spaces correctly / normalize all attendee data

### ISSUE THREAD

**Issue by srt32** [srt32/event_reporter#9]
The comparison should:

Be case insensitive, so "Mary" and "mary" would be found in the same search
Be insensitive to internal whitespace, but not external:
"John" and "John " are considered matches
"John Paul" and "Johnpaul" are not matches
Not do substring matches, so a find first_name Mary does not find a record with first name "marybeth"

**Comment by srt32** [comment]
Downcase the values when creating Attendees.   ,RegDate,first_Name,last_Name,Email_Address,HomePhone,Street,City,State,Zipcode

Then, downcase input from user

**Comment by MappingKat** [comment]
I worked on something like that last night.  I used the "comparable" method: http://ruby-doc.org/core-2.0.0/Comparable.html

class FirstName
  include Comparable
  attr_reader :first_name

  def initialize(first_name)  #automatically called
    @first_name = first_name.to_s.downcase.titleize
  end

  def to_s
    first_name
  end

  def <=>(other)
    to_s <=> other.to_s
  end
end

**Comment by MappingKat** [comment]
I need to test, but also can be applied to streets and cities:

class City
  include Comparable
  attr_reader :city

  def initialize(city)
    @city = city.to_s.tr("-.(),", "").capitalize #or titleize
  end

  def to_s
    city
  end

  def <=>(other)
    to_s <=> other.to_s
  end
end

class Street
  include Comparable
  attr_reader :street

  def initialize(street)
    @street = street.to_s.tr("-.(),", "").capitalize #... or titleize?
  end

  def to_s
    street
  end

  def <=>(other)
    to_s <=> other.to_s
  end
end

**Comment by srt32** [comment]
That's interesting.  Maybe it would be easier to just downcase and remove
all non-alphanumeric characters name, email, address, etc.
